### ISSUE TITLE
Merge / delete / supercede Urbit Proposals (UPs)

### ISSUE THREAD

**Issue by flowerornament** [urbit/UIPs#9]
Greetings @jalehman, I wonder if you were not aware of https://github.com/urbit/proposals when you made this? It obviously never really caught on, but just in case you completely missed it, it's there and you can delete, merge, or explicitly deprecate it if you feel like it.

Hope all's well 🌸

**Comment by jalehman** [comment]
I definitely was aware of that repository and it was definitely discussed when we started up this effort. UP's never really took off and have been effectively dead for four years, so starting fresh seemed like the right call. I'm going to go ahead and archive/deprecate that repository to make it clear that we've since moved on from it. Thanks for flagging!
